version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tacocloud"
      POSTGRES_USER: "pavel"
      POSTGRES_PASSWORD: "pavel"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"


