spring:
  application:
    name: taco-cloud

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:tacocloud
    generate-unique-name: false
    name: tacocloud

  h2:
    console:
      enabled: true


debug: false
