spring:
  application:
    name: taco-cloud

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    name: tacocloud
    username: pavel
    password: pavel
    generate-unique-name: false
  data:
    rest:
      base-path: /data-api

  jpa:
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    cache: false

logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: warn
    org.springframework.security: debug


