spring:
  application:
    name: taco-cloud

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    generate-unique-name: false
    name: tacocloud
    username: pavel
    password: pavel

  h2:
    console:
      enabled: true


debug: false
