spring:

  application:
    name: taco-cloud

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    name: tacocloud
    username: pavel
    password: pavel
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: create-drop

debug: false
